version: "3.9"

services:
    backend:
        build: ./crud_back
        container_name: crud-back
        ports:
            - "8000:8000"
        depends_on:
          - mongo
    frontend:
        build: ./crud_front
        container_name: crud-front
        ports:
            - "3000:3000"
        depends_on:
          - backend
    mongo:
      image: mongo:latest
      container_name: mongodb
      hostname: mongodb
      volumes:
        - .mongodb/data/db/:/data/db/
        - .mongodb/data/log/:/var/log/mongodb/
      restart: always
      env_file:
        - .env
      environment:
          MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
          MONGO_INITDB_DATABASE: ${DB_DATABASE}
      ports:
        - "27017:27017"
